apply plugin: "java-library"
apply plugin: "maven-publish"

ext.majorVersion = 7
ext.minorVersion = 0
ext.minecraftVersion = "1.21.8"
sourceCompatibility = 21
targetCompatibility = 21

// Suppiled by Jenkins
ext.buildNumber = System.env.BUILD_NUMBER == null ? "x"                : "$System.env.BUILD_NUMBER"
ext.mavenDirectory = System.env.MAVEN_DIR == null ? "$projectDir/repo" : "$System.env.MAVEN_DIR"

// Version used for distribution. Different from maven repo
group = "cat.nyaa"
archivesBaseName = "Yasui-mc$minecraftVersion"
version = "$majorVersion.$minorVersion.$buildNumber"

repositories {
    mavenCentral()
    maven { name 'PaperMC'; url 'https://repo.papermc.io/repository/maven-public/' }
}


dependencies {
    // Paper API
    compileOnly "io.papermc.paper:paper-api:$minecraftVersion-R0.1-SNAPSHOT"
}

compileJava {
    options.compilerArgs += ["-Xlint:deprecation"]
}

// publications
task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    archiveClassifier = 'sources'
}
processResources { // modify version string
    filesMatching("**/plugin.yml") {
        expand 'version': project.version
    }
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact sourcesJar
            groupId "cat.nyaa"
            artifactId "yasui"
            version "$majorVersion.$minorVersion-SNAPSHOT"
            from components.java
        }
    }
    repositories {
        maven {
            url "${mavenDirectory}"
        }
    }
}

