name: yasui
version: ${version}
main: cat.nyaa.yasui.Yasui
authors: [cylin]
api-version: '1.21'
commands:
  yasui:
    description: Yasui optimization control
permissions:
  yasui.admin:
    default: op